### ISSUE TITLE
Краш.

### ISSUE THREAD

**Issue by sidechko** [sidechko/epGameOfLife#1]
Во время работы приложения, может выбить ошибку:

> Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
> 	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2359)
> 	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2506)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:413)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:412)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:439)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:563)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342)
> 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
> 	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

Не ясно когда и где её выбивает, но есть подозрение на
```
    public void reloadRectangles() {
        for (int h = 0; h < bH; h++) {
            for (int w = 0; w < bW; w++) {
                String fill = mainBoard.cellsData[w][h] ? "#a5ffa1" : "#111111";
                rectangles[w][h].setFill(Paint.valueOf(fill));
            }
        }
    }
```

**Comment by sidechko** [comment]
Нужно запустить долгий тест, что бы узнать, крашится или нет.
